# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a42581e97bb3e602dcb06e40d500df03"
name = "fx-test-app"
handle = "fx-test-app"
application_url = "https://gibraltar-subdivision-nav-ranks.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts, write_discounts_allocator_functions, read_products"

[auth]
redirect_urls = [
  "https://gibraltar-subdivision-nav-ranks.trycloudflare.com/auth/callback",
  "https://gibraltar-subdivision-nav-ranks.trycloudflare.com/auth/shopify/callback",
  "https://gibraltar-subdivision-nav-ranks.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
